version: '3'

services:
 backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database


 client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend


 database:
    image: "mongo"
    environment:
      POSTGRES_USER: "aakansha2000"
      POSTGRES_PASSWORD: "root123"
      POSTGRES_DB: "invoice"
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/var/lib/mongo/data"

volumes:
 db-data: